---
collections:
  - name: community.general
  - name: redhat.rhel_system_roles
  - name: redhat.rhel_idm
  - name: redhat.satellite_operations
  - name: redhat.openshift
  - name: redhat.openshift_virtualization  
  - name: redhat.insights                               
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.controller

