---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--pre -c -v"
  PKGMGR_PRESERVE_CACHE: "always"

dependencies:
  python: requirements.txt
  system: bindep.txt
  galaxy: requirements.yml

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

      #options:
      #  package_manager_path: /usr/bin/microdnf

additional_build_files:
      - src: files/ansible.cfg
        dest: configs

additional_build_steps:
  prepend_builder:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.15-for-rhel-8-x86_64-rpms.enabled=true"
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  prepend_final:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.15-for-rhel-8-x86_64-rpms.enabled=true"
...
